env = "dev"
slack_bot_token_parameter = "/topleft/llm_slackbot/dev/SLACK_BOT_TOKEN"
slack_signing_secret_parameter = "/topleft/llm_slackbot/dev/SLACK_SIGNING_SECRET"
slack_slash_command = "/ask-llm"
kb_embedding_model_id = "amazon.titan-embed-text-v2:0"
rag_model_id = "amazon.nova-2-lite-v1:0"
inference_profile_id = "global.amazon.nova-2-lite-v1:0"